[package]
name = "roughdb"
license = "Apache-2.0"
version = "0.1.0-dev"
edition = '2021'
repository = "https://github.com/wcgw/roughdb/"
authors = ["Alex Snaps <alex@wcgw.dev>"]

[dependencies]
bumpalo = "3.12.1"